batch_size: 64 # how many independent sequences will we process in parallel?
block_size: 64 # what is the maximum context length for predictions?
max_iters: 40000
eval_interval: 1500
learning_rate: 3e-4
eval_iters: 300
n_embd: 128 # n_embd needs to be divisible by n_head.
n_head: 8
n_layer: 3
dropout: 0.3 # dropout% is dropped out
data_path: '../data/input.txt'