batch_size: 64 # how many independent sequences will we process in parallel?
block_size: 24 # what is the maximum context length for predictions?
max_iters: 20000
eval_interval: 1000
learning_rate: 3e-4
eval_iters: 200
n_embd: 42 # n_embd needs to be divisible by n_head.
n_head: 6
n_layer: 3
dropout: 0.1 # dropout% is dropped out
data_path: '../data/input.txt'